---
- name: Provision Debian 11 General
  hosts: 127.0.0.1
  become: yes

  tasks:
  - name: install required packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
  
  - name: install pip docker sudo
    pip:
      name: docker
      state: latest

  - name: install pip docker
    become: false
    pip:
      name: docker
      state: latest
  
  - name: add docker gpg apt-key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
  
  - name: Add Docker Repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      state: present
  
  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: yes
  
  - name: install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: a+x

  - name: add current user to docker group
    user:
      name: "packer"
      groups: docker
      append: yes